### ISSUE TITLE
Icon scaling issue when used in Button component

### ISSUE THREAD

**Issue by kieranhall** [dusk-network/rusk#1637]
**Describe the bug**
It appears some CSS is missing for the Button component when used with an icon.  The `:active` and `:enabled` states (also the `.dusk-button--active`) appear affected

**Expected behaviour**
Icon to button to scale together smoothly.

**Potential Solution**

```css
/* added the :hover:active case otherwise the rule above takes precedence */
.dusk-icon-button:not(.dusk-icon-button-labeled):enabled:hover:active,
.dusk-icon-button:not(.dusk-icon-button-labeled):enabled:active,
.dusk-icon-button:not(.dusk-icon-button-labeled).dusk-anchor-button:not(
    .dusk-anchor-button--disabled
  ):active,
.dusk-button--type--toggle.dusk-button--type--toggle--active {
  transform: scale(0.9, 0.9);
}
```

**Additional context**
We will address Button component refactoring in Duskit, this is just a fix needed for presentation here in the wallet.
