### ISSUE TITLE
Using `base_state` generates corrupted state

### ISSUE THREAD

**Issue by herr-seppia** [dusk-network/rusk#754]
**Describe the bug**
Using rusk-recovery-state with an init toml that manipulate a base state, result in a corrupted state.
The above mentioned state is working properly for transacting, but raise an error as soon as the stake contract is called.

**To Reproduce**
- Generate a preliminary state to use as base_state (all toml are at the end of the issue)
```
rusk-recovery-state -I ./genesis.toml -o /tmp/genesis.zip
```
- Generate a manipulated state starting from the previous one
```
rusk-recovery-state -I ./state.toml -o /tmp/state.zip
```
- Launch a single cluster with the current state
```
bin/rusk -c rusk.toml -s /tmp/state.zip &
bin/dusk --config dusk.toml
```
- Create a staking transaction
- The transaction fails with this error
```
code: Other
contractId: 0x0100000000000000000000000000000000000000000000000000000000000000
data: WebAssembly translation error: Error when converting wat: expected at least one module field
     --> <anon>:1:1
      |
    1 | 
      | ^
```
if applicable add a *minimum reproducible example*

**Additional context**
This happens only if base_state is used with additional manipulation (balances, stakes, etc)
If the toml specify only the base_state, it works
If the toml doesn't specify the base_statte, it works

genesis.toml
```toml
[acl.stake]
owners = []
allowlist = []
```

state.toml
```toml
base_state = "file:///tmp/genesis.zip"

[acl.stake]
owners = [
    '22p9MSeCwzrGtSff3TYPELufsGxU4oumgkHd4XqNTq5tuHmJ3aTPJErA7nF6ns4vqW295y3SXY9FdZd68bXP5q82AAEmCustZvD3mbb8K32Eawm3GNmUkzVLU7t24tCe5atj',
]
allowlist = [
    '22p9MSeCwzrGtSff3TYPELufsGxU4oumgkHd4XqNTq5tuHmJ3aTPJErA7nF6ns4vqW295y3SXY9FdZd68bXP5q82AAEmCustZvD3mbb8K32Eawm3GNmUkzVLU7t24tCe5atj',
]

[[balance]]
address = '5i9RZjT87TLa1BtWXRRoFy3FoMzFHiXT3GWasHdUaxuo3YapUKYeXXiY1yuAeKng2hmxxaYsGNhKhjyrE9KYTSE7'
seed = 0xdead_beef
notes = [10_000_000_000_000]

[[stake]]
address = '22p9MSeCwzrGtSff3TYPELufsGxU4oumgkHd4XqNTq5tuHmJ3aTPJErA7nF6ns4vqW295y3SXY9FdZd68bXP5q82AAEmCustZvD3mbb8K32Eawm3GNmUkzVLU7t24tCe5atj'
amount = 1_000_000_000_000
```
[configs.zip](https://github.com/dusk-network/rusk/files/9817888/configs.zip)
