### ISSUE TITLE
Update to `piecrust` version `0.5`

### ISSUE THREAD

**Issue by ureeves** [dusk-network/rusk#883]
#### Summary
This is necessary to allow the registration of contract `owners`, which in turn is necessary for implementing the [fee market](#880).

#### Possible solution design or implementation
```toml
piecrust = "0.5"
piecrust-uplink = "0.5"
```
